import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "sonner";
import Hero from "@/components/Hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
<<<<<<< HEAD
        <Hero></Hero>
=======
        {/* <Hero></Hero> */}
>>>>>>> 28f1c9522c1a1c5633ca001bdfad0d70011f2250
        {children}
        <Toaster></Toaster>
      </body>
    </html>
  );
}
